services:
  # Backend Web Service
  - type: web
    name: payroll-backend
    repo: https://github.com/rahulraj24590/Payroll-Management-System
    plan: free
    env: node
    region: ohio
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d

  # Frontend Static Site
  - type: web
    name: payroll-frontend
    repo: https://github.com/rahulraj24590/Payroll-Management-System
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
